version: 2.1

orbs:
  android: circleci/android@1.0.3

commands:
  setup-openjdk11:
    description: |
      Setup the OpenJDK 11 Runtime
    steps:
    - run:
        name: Install OpenJDK 11
        command: |
          sudo apt update && sudo apt install default-jdk
  setup-bazel:
    description: |
      Setup the Bazel build system used for building Android projects
    steps:
    - run:
        name: Add Bazel Apt repository
        command: |
          sudo apt install curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - run:
        name: Install Bazel from Apt
        command: |
          sudo apt update && sudo apt install bazel-5.3.0
jobs:
  build-and-test:
    docker:
    - image: cimg/android:2022.09.2
    steps:
    - checkout
    - android/accept-licenses
    - setup-openjdk11
    - setup-bazel
    - run:
        name: Build All
        command: bazel-5.3.0 build --jobs=1 //...
    - run:
        name: Test All
        command: bazel-5.3.0 test --jobs=1 --test_output=errors //...

workflows:
  githubci:
    jobs:
    - build-and-test
